// Generated by CoffeeScript 1.6.3
(function() {
  var exports;

  enchant();

  exports = this;

  window.onload = function() {
    var BOUNCE, Floor, GAME_HEIGHT, GAME_WIDTH, GRAVITY, LIO_DEFAULT_Y, Lio, game, img, lio, lio_imgs, _i, _len;
    GAME_WIDTH = 320;
    GAME_HEIGHT = 320;
    GRAVITY = 20;
    BOUNCE = 0.01;
    LIO_DEFAULT_Y = 20;
    lio = null;
    lio_imgs = [
      {
        width: 80,
        height: 50,
        url: "img/lio00.png"
      }
    ];
    Lio = enchant.Class.create(PhyBoxSprite, {
      initialize: function(x, y) {
        var img, img_num;
        if (x == null) {
          x = GAME_WIDTH / 2;
        }
        if (y == null) {
          y = GAME_HEIGHT / 2;
        }
        img_num = 0;
        img = lio_imgs[img_num];
        PhyBoxSprite.call(this, img.width, img.height, enchant.box2d.DYNAMIC_SPRITE, 1.0, 1.0, BOUNCE, false);
        this.image = game.assets[img.url];
        this.position = {
          x: x,
          y: y
        };
        return game.rootScene.addChild(this);
      },
      update: function() {}
    });
    Floor = enchant.Class.create(PhyBoxSprite, {
      initialize: function() {
        PhyBoxSprite.call(this, GAME_WIDTH - 20, 20, enchant.box2d.STATIC_SPRITE, 1.0, 1.0, 0.0, true);
        this.x = 10;
        this.y = GAME_HEIGHT - this.height;
        this.backgroundColor = "green";
        return game.rootScene.addChild(this);
      }
    });
    game = enchant.Core(GAME_WIDTH, GAME_HEIGHT);
    game.fps = 30;
    game.rootScene.backgroundColor = "aqua";
    for (_i = 0, _len = lio_imgs.length; _i < _len; _i++) {
      img = lio_imgs[_i];
      game.preload(img.url);
    }
    game.onload = function() {
      var world;
      world = new PhysicsWorld(0.0, GRAVITY);
      new Floor;
      game.rootScene.addEventListener('touchstart', function(e) {
        return exports.lio = new Lio(e.x, LIO_DEFAULT_Y);
      });
      game.rootScene.addEventListener('touchmove', function(e) {
        if (exports.lio == null) {
          return;
        }
        return exports.lio.position = {
          x: e.x,
          y: exports.lio_DEFAULT_Y
        };
      });
      game.rootScene.addEventListener('touchend', function() {
        if (exports.lio == null) {
          return;
        }
        return exports.lio.setAwake(true);
      });
      return game.rootScene.onenterframe = function(e) {
        return world.step(game.fps);
      };
    };
    return game.start();
  };

}).call(this);
